### ISSUE TITLE
Hardcoded <iq> 'id' attribute

### ISSUE THREAD

**Issue by Zash** [ChatSecure/RubDub#8]
The response `id` attribute is hardcoded in [`src/xmpp.js`](https://github.com/ChatSecure/RubDub/blob/f68f8862ef8abdd71f92938eb29a713b5943d626/src/xmpp.js#L56).

The response `id` attribute must be equal to the one in the request.

[XMPP Core - §8.2.3.  IQ Semantics](http://xmpp.org/rfcs/rfc6120.html#stanzas-semantics-iq) states:

>  The response MUST preserve the 'id' attribute of the request (or be empty if the generated stanza did not include an 'id' attribute).

**Comment by davidchiles** [comment]
Thanks for spotting this.
